import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Footer from "../components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex justify-between p-4 bg-[#e2f7ff]">
          <span className="font-bold">KSSS</span>
          <nav className="flex gap-4 font-semibold">
          <Link href="/"> HOME </Link>
          <Link href="/timeline"> TIMELINE </Link>
          <Link href="/"> YEAR BOOKS </Link>
          <Link href="/about-us"> About Us</Link>
          </nav>
        </header>
        <main>
        {children}
        </main>
        <Footer/>
        </body>
    </html>
  );
}
